font_family Monaspace Argon NF
font_size 12
focus_follows_mouse yes

map ctrl+t new_tab
map ctrl+a select_all

map ctrl+shift+up scroll_to_prompt -1
map ctrl+shift+down scroll_to_prompt 1

map ctrl+\ launch --location=vsplit
map ctrl+' launch --location=hsplit

map ctrl+x close_tab


# BEGIN_KITTY_THEME
# Ayu Mirage
include current-theme.conf
# END_KITTY_THEME
