wallpaper {
    monitor = DP-2
    path = ~/pictures/wallpapers/ISD/ISD double color.jpg
}
wallpaper {
    monitor = DP-3
    path = ~/pictures/wallpapers/ISD/ISD two (crop).png
}
splash=false
ipc = on
